version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: crypto-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      - CLICKHOUSE_DB=crypto_analytics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./docker/clickhouse-config.xml:/etc/clickhouse-server/config.xml:ro
    networks:
      - crypto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  crypto-app:
    build: .
    container_name: crypto-app
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DATABASE=crypto_analytics
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - DEBUG=${DEBUG:-false}
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - crypto-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  data-scheduler:
    build: .
    container_name: crypto-data-scheduler
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DATABASE=crypto_analytics
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - crypto-network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    command: ["python", "-m", "app.scheduler"]

  nginx:
    image: nginx:alpine
    container_name: crypto-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - crypto-app
    networks:
      - crypto-network
    restart: unless-stopped

volumes:
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local

networks:
  crypto-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16