version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto-postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=crypto_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - crypto-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crypto_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data_dev:
    driver: local

networks:
  crypto-network-dev:
