"""initial

Revision ID: 0e6c9264ac14
Revises: 
Create Date: 2025-09-07 22:31:33.318270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6c9264ac14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptocurrencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('blockchain', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptocurrencies_symbol'), 'cryptocurrencies', ['symbol'], unique=False)
    op.create_table('defi_protocols',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('chain', sa.String(length=50), nullable=True),
    sa.Column('tvl', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('native_token_id', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['native_token_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defi_protocols_category'), 'defi_protocols', ['category'], unique=False)
    op.create_index(op.f('ix_defi_protocols_chain'), 'defi_protocols', ['chain'], unique=False)
    op.create_index(op.f('ix_defi_protocols_name'), 'defi_protocols', ['name'], unique=False)
    op.create_index(op.f('ix_defi_protocols_native_token_id'), 'defi_protocols', ['native_token_id'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cryptocurrency_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_supply', sa.DECIMAL(precision=30, scale=2), nullable=True),
    sa.Column('circulating_supply', sa.DECIMAL(precision=30, scale=2), nullable=True),
    sa.Column('max_supply', sa.DECIMAL(precision=30, scale=2), nullable=True),
    sa.Column('ath', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('atl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ath_date', sa.DateTime(), nullable=True),
    sa.Column('atl_date', sa.DateTime(), nullable=True),
    sa.Column('roi_percentage', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_cryptocurrency_id'), 'market_data', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cryptocurrency_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('volume_24h', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('price_change_24h', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('price_change_percentage_24h', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['cryptocurrency_id'], ['cryptocurrencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_cryptocurrency_id'), 'price_history', ['cryptocurrency_id'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('tvl_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('protocol_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tvl', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('tvl_change_24h', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('tvl_change_percentage_24h', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['defi_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tvl_history_protocol_id'), 'tvl_history', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_tvl_history_timestamp'), 'tvl_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tvl_history_timestamp'), table_name='tvl_history')
    op.drop_index(op.f('ix_tvl_history_protocol_id'), table_name='tvl_history')
    op.drop_table('tvl_history')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_cryptocurrency_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_cryptocurrency_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_defi_protocols_native_token_id'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_name'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_chain'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_category'), table_name='defi_protocols')
    op.drop_table('defi_protocols')
    op.drop_index(op.f('ix_cryptocurrencies_symbol'), table_name='cryptocurrencies')
    op.drop_table('cryptocurrencies')
    # ### end Alembic commands ###