"""add new fields

Revision ID: d693b33f0e20
Revises: 0e6c9264ac14
Create Date: 2025-09-10 21:47:38.963393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd693b33f0e20'
down_revision = '0e6c9264ac14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('spread_percentage', sa.DECIMAL(precision=10, scale=6), nullable=True))
    op.add_column('market_data', sa.Column('liquidity_score', sa.DECIMAL(precision=10, scale=4), nullable=True))
    op.add_column('price_history', sa.Column('bid_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('price_history', sa.Column('bid_size', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('price_history', sa.Column('ask_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('price_history', sa.Column('ask_size', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('price_history', sa.Column('prev_price_24h', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('price_history', sa.Column('turnover_24h', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('price_history', sa.Column('usd_index_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'usd_index_price')
    op.drop_column('price_history', 'turnover_24h')
    op.drop_column('price_history', 'prev_price_24h')
    op.drop_column('price_history', 'ask_size')
    op.drop_column('price_history', 'ask_price')
    op.drop_column('price_history', 'bid_size')
    op.drop_column('price_history', 'bid_price')
    op.drop_column('market_data', 'liquidity_score')
    op.drop_column('market_data', 'spread_percentage')
    # ### end Alembic commands ###